### ISSUE TITLE
Dependant Package "defaults-deep" is flagged as having a 'moderate' issue

### ISSUE THREAD

**Issue by NorthernMan54** [jonschlinkert/expand-pkg#2] opened 2019-02-12 14:26 UTC
Prior to publishing one of my applications today, ran into this warning today.

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ defaults-deep                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ No patch available                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ update                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ update > base-cli-process > base-config-process >            │
│               │ base-config-schema > base-pkg > expand-pkg > defaults-deep   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/778                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

This is just an FYI, I opened an issue against defaults-deep as well

https://github.com/jonschlinkert/defaults-deep/issues/6

**Comment by jonschlinkert** [comment] 2019-02-14 18:24
wrong library and a duplicate of the library you linked to

**Closed as completed by jonschlinkert** 2019-02-14 18:24 UTC
